# Generated by Django 4.2.11 on 2024-03-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=60)),
                ('pdop', models.DateField()),
                ('pavail', models.IntegerField()),
                ('ptotal', models.IntegerField()),
                ('poriginalcost', models.IntegerField()),
                ('psellingcost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=60)),
                ('custadd', models.CharField(max_length=60)),
                ('cpname', models.CharField(max_length=60)),
                ('cpquantity', models.IntegerField()),
                ('cpeach', models.IntegerField()),
                ('cptotal', models.IntegerField()),
                ('cpdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_info', models.TextField()),
                ('request_desc', models.TextField()),
                ('requester_name', models.CharField(max_length=60)),
                ('requester_add1', models.TextField()),
                ('requester_add2', models.TextField()),
                ('requester_city', models.CharField(max_length=60)),
                ('requester_state', models.CharField(max_length=60)),
                ('requester_zip', models.IntegerField()),
                ('requester_email', models.EmailField(max_length=60)),
                ('requester_mobile', models.BigIntegerField()),
                ('request_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=60)),
                ('empCity', models.CharField(max_length=60)),
                ('empMobile', models.BigIntegerField()),
                ('empEmail', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=60)),
                ('r_email', models.EmailField(max_length=60)),
                ('r_password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AssignWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_info', models.TextField()),
                ('request_desc', models.TextField()),
                ('requester_name', models.CharField(max_length=60)),
                ('requester_add1', models.TextField()),
                ('requester_add2', models.TextField()),
                ('requester_city', models.CharField(max_length=60)),
                ('requester_state', models.CharField(max_length=60)),
                ('requester_zip', models.IntegerField()),
                ('requester_email', models.EmailField(max_length=60)),
                ('requester_mobile', models.BigIntegerField()),
                ('assign_date', models.DateField()),
                ('assign_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.technician')),
                ('request', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.submitrequest')),
            ],
        ),
    ]
